#!/bin/bash

docker cp conjur/conjur.yml conjur_client_1:/tmp/
docker-compose exec client conjur policy load --replace root /tmp/conjur.yml

docker cp conjur/ansible.yml conjur_client_1:/tmp/
docker-compose exec client conjur policy load ansible /tmp/ansible.yml  | tee ansible.out

docker cp conjur/server.yml conjur_client_1:/tmp/
docker-compose exec client conjur policy load server /tmp/server.yml