#!/bin/bash

# Wait for bootstrap to complete
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

# Ansible
echo "=== [START] apt update and installs ==="
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install sshpass ansible git curl -y
echo "=== [FINISH] apt update and installs ==="

echo "=== [START] Export env vars to /root/.bashrc ==="
echo "export ANSIBLE_HOST_KEY_CHECKING=False" >> /root/.bashrc
echo "=== [FINISH] Export env vars to /root/.bashrc ==="

# Setup environment
echo "=== [START] Setup environment ==="
git clone https://github.com/quincycheng/katacoda-env-conjur-ansible-ssh.git 
mv katacoda-env-conjur-ansible-ssh/* /root
rm -rf katacoda-env-conjur-ansible-ssh
echo "=== [FINISH] Setup environment ==="

# Conjur
echo "=== [START] Conjur initial setup ==="
curl -o docker-compose.yml https://quincycheng.github.io/docker-compose.quickstart.yml
docker-compose pull
docker-compose run --no-deps --rm conjur data-key generate > data_key
docker pull postgres:9.6
echo "=== [FINISH] Conjur initial setup ==="

# Add service01 account
echo "=== [START] Add service01 account ==="
useradd -m -d /home/service01 service01
echo 'service01:W/4m=cS6QSZSc*nd' | chpasswd
sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
mkdir -p /home/service01/.ssh
ssh-keygen -t rsa -b 4096 -N "" -f /home/service01/.ssh/id_rsa
touch /home/service01/.ssh/authorized_keys
cat /home/service01/.ssh/id_rsa.pub >> /home/service01/.ssh/authorized_keys
chmod 600 /home/service01/.ssh/authorized_keys
chown -R service01:service01 /home/service01/.ssh
service ssh restart
echo "=== [FINISH] Add service01 account ==="