#!/bin/bash

export COMPOSE_INTERACTIVE_NO_CLI=1

docker-compose exec -T client conjur variable values add server/host01/host "host01"
docker-compose exec -T client conjur variable values add server/host01/user "service01"
docker-compose exec -T client conjur variable values add server/host01/pass "W/4m=cS6QSZSc*nd"
docker-compose exec -T client conjur variable values add server/host02/host "host02"
docker-compose exec -T client conjur variable values add server/host02/user "service02"
docker-compose exec -T client conjur variable values add server/host02/pass "5;LF+J4Rfqds:DZ8"
