#!/bin/bash

# check
echo "Checking the solution of the challenge"
whoami=$(conjur authn whoami)
if [ "$whoami" != "admin" ]; then
  fail-message "Your challenge failed because you did not properly authenticate as admin to the Conjur service."
fi