#!/bin/bash
set -euxo pipefail

export COMPOSE_INTERACTIVE_NO_CLI=1

# check
echo "Checking the solution of the challenge"
whoami=$(docker-compose exec -T client conjur authn whoami)
if [ "$whoami" != "{\"account\":\"demo\",\"username\":\"admin\"}" ]; then
  fail-message "Your challenge failed because you did not properly authenticate as admin to the Conjur service."
fi