#!/bin/bash

docker-compose exec client bash -c "echo yes | conjur init -u http://host01:8080 -a demo"
api_key="$(grep API conjur/admin.out | cut -d: -f2 | tr -d ' \r\n')"
docker-compose exec client conjur authn login -u admin -p "$api_key"
