#!/bin/bash
set -euxo pipefail

# check
echo "Checking the solution of the challenge"
if [ ! -f /root/insecure-playbook/inventory ]; then
  fail-message "Your challenge failed because you did not create an inventory file for Ansible"
fi

if [ ! -f /root/insecure-playbook/insecure-playbook.yml ]; then
  fail-message "Your challenge failed because you did not create an insecure-playbook.yml Ansible playbook file"
fi