#!/bin/bash
set -exu

grep -q "curl \"\$URL\"/pets" /root/.bash_history || fail-message "The command curl \"\$URL/pets\" was not executed."

grep -q "curl -d \"{\"name\": \"\$(shuf -n 1 /usr/share/dict/american-english)\"}\" -H \"Content-Type: application/json\" \"\$URL\"/pet" /root/.bash_history || fail-message "The command to add a new message with a random name was not executed."

grep -q "curl -s \"\$URL\"/pets | jq ." /root/.bash_history || fail-message "The command to list all messages was not executed."