#!/bin/bash -l

DEBIAN_FRONTEND=noninteractive apt-get install wamerican -y

if [[ ! -f /usr/share/dict/american-english ]]; then
  echo "Dictionary file /usr/share/dict/american-english does not exist."
  exit 1
fi