#!/bin/bash

git clone https://github.com/quincycheng/katacoda-env-conjur-ansible-ssh.git 
mv katacoda-env-conjur-ansible-ssh/* .
rm -rf katacoda-env-conjur-ansible-ssh
chmod +x conjur/setupConjur.sh
pushd conjur || exit 1
    ./setupConjur.sh
popd || exit 1