#!/bin/bash

while ! nc -z host01 8080; do
    echo "Waiting for port 8080 to become reachable on host01"
    sleep 1
done

docker-compose exec -T conjur conjurctl account create demo > conjur/admin.out