version: "3"
virtualmachines:
- name: server
  image: instruqt/k3s-v1-21-4
  shell: /bin/bash
  machine_type: n1-standard-4
- name: worker
  image: instruqt/k3s-v1-21-4
  shell: /bin/bash
  environment:
    K3S_CONTROL_PLANE_HOSTNAME: server
  machine_type: n1-standard-4
