version: "3"
containers:
- name: host02
  image: ubuntu
  shell: /bin/bash
  memory: 256
virtualmachines:
- name: host01
  image: instruqt/docker-2010
  shell: /bin/bash
  machine_type: n1-standard-1
