#!/bin/bash

# check
echo "Checking the solution of the challenge"
if [ ! -f /root/conjur/hftoken ]; then
  fail-message "Your challenge failed because you did not generate a host factory token"
fi

if [ ! -f /root/conjur/inventory ]; then
  fail-message "Your challenge failed because you did not create an inventory file for Ansible"
fi

if [ ! -f /root/conjur/grant_conjur_id.yml ]; then
  fail-message "Your challenge failed because you did not create a grant_conjur_id.yml Ansible playbook file"
fi