#!/bin/bash
set -euxo pipefail

# check
echo "Checking the solution of the challenge"
if [ ! -f /root/conjur/hftoken ]; then
  fail-message "Your challenge failed because you did not generate a host factory token"
fi

if [ ! -f /root/conjur/inventory ]; then
  fail-message "Your challenge failed because you did not create an inventory file for Ansible"
fi

if [ ! -f /root/conjur/grant_conjur_id.yml ]; then
  fail-message "Your challenge failed because you did not create a grant_conjur_id.yml Ansible playbook file"
fi

if [ ! -f /etc/conjur.conf ]; then
  fail-message "Your challenge failed because dynamic enrollment failed to create /etc/conjur.conf"
fi

if [ ! -f /etc/conjur.identity ]; then
  fail-message "Your challenge failed because dynamic enrollment failed to create /etc/conjur.identity"
fi